---
title: "Bob Ross Case Study Hints"
author: "Miranda Rintoul"
date: "2024-11-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. Elements by Episode

## 1.1 Are Any Titles Repeated?

* Is the variable `TITLE` a unique identifier?
* Use the `count` function to count rows, and `filter()` or `arrange()` to look for repeats.

## 1.2 Which Features Appear The Most?

* What are the features that appear in the paintings made by Bob Ross himself?
* Use `filter()` to find only the paintings made by Bob Ross himself.
* We want to `select()` only the relevant features - we don't want any of the guest columns or any of the frame columns.

* Write code which produces a dataframe indicating the percentage of paintings in which each feature appears. 
* use `pivot_longer()` to make each row a painting-feature combination.
* after pivoting, we can `group_by()` feature and then `summarize()`.

## 1.3 Visualization

* `geom_col()` should be used instead of `geom_bar()` when we are specifying both x and y.
* `reorder()` by percentage needs to be inside `aes()`.
* The percentage labels are a variable aesthetic and they also need to go in `aes()`.
* Try to change color, x scale, remove grid, and add appropriate titles.


# 2. Colors by Episode

## 2.1 Visualization

* Create a plot visualizing the distribution of the number of colors used, `num_colors`.
* Now we can use `geom_bar()` because we want to take a count across different values of x.

## 2.2 What's that Outlier?

* Do some in-class investigation into the outlier (the painting with 1 color)
* Use `filter()` get the correct painting and view the links to the painting video and image.


# 3. Joining 

* Use `str_sub()` to extract elements from a string
* The datasets need to be joined by *both* episode number and title

## 3.1 Visualization

* Your code can be largely the same as the one used to make the visualization in problem 2.1.



