---
title: "live_week3"
author: "Sahifa"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = TRUE)
library(tidyverse)
```
# Monday

```{r}
mendota = read_csv("../data/lake-mendota-winters-2025.csv")
```

We will use the in-built tidyverse dataset called `mpg`.

```{r}
# step 1: stepping up the canvas

ggplot()
```

```{r}
#step 2: specify the data

ggplot(data = mpg)
```

```{r}
#step 3: specify the mappings

ggplot(data = mpg, mapping = aes(x = cty, y = hwy))
```

```{r}
#step 4: specify the type of plot

ggplot(data = mpg, mapping = aes(cty, hwy)) + 
  geom_point(col = "red") +
  geom_line()
```

# Wednesday

```{r}
# adding color to the points depoending on the vehicles cylinder

ggplot(mpg, mapping = aes(cty, hwy, col = as.factor(cyl))) + 
  geom_point() +
  geom_line()
```

# variable vs constant aesthetic

```{r}
ggplot(data = mpg, mapping = aes(cty, hwy)) + 
  geom_point(col = "red") +
  geom_line()

ggplot(mpg, mapping = aes(cty, hwy, col = as.factor(cyl))) + 
  geom_point() +
  geom_line()
```

# global vs local aesthetic

```{r}
ggplot(data = mpg, mapping = aes(cty, hwy)) + 
  geom_point(col = "red") + # local aesthetic because the color is applied to only the points and not the lines
  geom_line()

ggplot(mpg, mapping = aes(cty, hwy, col = as.factor(cyl))) +# global aethetic because the color gets applied to both the points and lines
  geom_point() +
  geom_line()
```

```{r}
ggplot() + 
  geom_point(data = mpg, mapping = aes(cty, hwy), col = "red") +
  geom_line()
```

```{r}
ggplot(mpg, aes(x = cty, y = hwy)) +
  geom_point(color = "purple", size = 4)
```

# Two variable:

- geom_point()
- geom_line()
- geom_smooth(): thsi function smakes trendlines (line of best fit)

```{r}
ggplot(mpg, aes(cty, hwy)) +
  geom_point() +
  geom_smooth()

ggplot(mpg, aes(cty, hwy)) +
  geom_point() +
  geom_smooth(se = F, method = "lm")
```

- geom_col():

```{r}
ggplot(count(mpg, class), aes(class, n)) + 
  geom_col(color = "purple", fill = "yellow") # the argument fill is used for shaped plots, where the shapes have an area that can be colored 
```





