---
title: "live_tidyr_004"
author: "Sahifa"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
players = tibble(
  player = c("Erling Haaland", "Kevin De Bruyne", "Lionel Messi", "James LeBron"),
  goals = c(36, 7, NA, 40),
  assists = c(8, 16, 4, NA),
  games = c(35, 32, 30, NA)
)

players
```

- drop_na(): thsi function removes th erows that have NA s either from the whole or from column specified

```{r}
players %>% filter(!is.na(goals) & !is.na(assists))

players %>% drop_na()

players %>% drop_na(goals)
```

# pivoting

```{r}
players
```

pivoting to a longer dataset: one column for the id and one column for the column names and one column for the values

```{r}
players %>% pivot_longer(c(goals, assists, games), names_to = "Game_info", values_to = "Score")

players %>% pivot_longer(goals:games , names_to = "Game_info", values_to = "Score")

players %>% pivot_longer(-player, names_to = "Game_info", values_to = "Score")
```

```{r}
player_wide_default = players %>% pivot_longer(-player)
player_wide = players %>% pivot_longer(-player, names_to = "Game_info", values_to = "Score")
```

pivoting from a long dataset to a wide dataset

```{r}
player_wide_default %>% pivot_wider()

player_wide %>% pivot_wider(names_from = Game_info, values_from = Score)
```



```{r}
# go from table1 to table2

table1 %>% pivot_longer(cases:population, names_to = "type", values_to = "count")
```

```{r}
# go from table2 to table1

table2 %>% pivot_wider(names_from = "type", values_from = count)
```

```{r}
# join this with table1 or table2 such that you have country, year, rate, cases and population and only common rows

table3 %>% inner_join()
```

```{r}
nchar(players$player)
```




